# Generated by Django 5.0.4 on 2024-04-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=20)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('vagas', models.IntegerField()),
                ('escolaridade', models.CharField(max_length=9)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('data_emissao', models.DateField()),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('uf_emissao', models.CharField(max_length=2)),
                ('filiacao', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.turma')),
            ],
        ),
    ]
