# Generated by Django 5.0.4 on 2024-04-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=20)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('data_emissao', models.DateField()),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('uf_emissao', models.CharField(max_length=2)),
                ('nome_mae', models.CharField(max_length=100)),
                ('nasc_mae', models.DateField()),
                ('nome_pai', models.CharField(max_length=100)),
                ('nasc_pai', models.DateField()),
                ('nivel_escola', models.CharField(max_length=24)),
                ('instituicao', models.CharField(max_length=100)),
                ('id_contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.contatos')),
                ('id_endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.enderecos')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turmas')),
            ],
        ),
    ]
