# Generated by Django 5.0.4 on 2024-04-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=20)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=12)),
                ('data_emissao', models.DateField()),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('uf_emissao', models.CharField(max_length=2)),
                ('nome_mae', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('escolaridade', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('celular', models.CharField(max_length=16)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
        ),
    ]
