# Generated by Django 5.0.4 on 2024-04-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nivel_escolaridade',
            new_name='escolaridade',
        ),
    ]
