# Generated by Django 5.0.4 on 2024-04-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome_mae',
            new_name='filiacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_pai',
        ),
    ]
