# Generated by Django 5.0.4 on 2024-04-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='rg',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
