# Generated by Django 5.0.4 on 2024-04-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
        migrations.RenameModel(
            old_name='Enderecos',
            new_name='Endereco',
        ),
        migrations.RenameModel(
            old_name='Turmas',
            new_name='Turma',
        ),
    ]
