# Generated by Django 5.0.4 on 2024-04-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_alunos_aluno_rename_contatos_contato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nivel_escola',
            new_name='nivel_escolaridade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nasc_mae',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nasc_pai',
        ),
    ]
