# Generated by Django 5.0.4 on 2024-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nivel_escola_aluno_nivel_escolaridade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='horario',
            new_name='horario_entrada',
        ),
        migrations.AddField(
            model_name='turma',
            name='horario_saida',
            field=models.TimeField(default=None),
        ),
    ]
