from django import forms

class Form(forms.Form):
    nome = forms.CharField(label='Nome completo *', max_length=100)
    nascimento = forms.CharField(label='Data de nascimento *', max_length=10)
    cpf = forms.CharField(label='CPF *', max_length=14)
    rg = forms.CharField(label='RG *', max_length=12)
    data_emissao = forms.CharField(label='Data de emissão *', max_length=10)
    orgao_emissor = forms.CharField(label='Órgão emissor *', max_length=100)
    uf_emissao = forms.CharField(label='UF de emissão *', max_length=2)
    nome_mae = forms.CharField(label='Nome da mãe *', max_length=100)
    nome_pai = forms.CharField(label='Nome do pai', max_length=100)
    escolaridade = forms.CharField(label='Nível de escolaridade *', max_length=24)
    email = forms.EmailField(label='E-mail *')
    telefone = forms.CharField(label='Telefone', max_length=14)
    celular = forms.CharField(label='Celular *', max_length=16)
    cep = forms.CharField(label='CEP *', max_length=10)
    rua = forms.CharField(label='Logradouro *', max_length=100)
    numero = forms.IntegerField(label='Número *')
    complemento = forms.CharField(label='Complemento', max_length=100)
    bairro = forms.CharField(label='Bairro *', max_length=100)
    cidade = forms.CharField(label='Cidade *', max_length=100)
    uf = forms.CharField(label='UF *', max_length=2)
    id_turma = forms.IntegerField(label='')