# Generated by Django 5.0.6 on 2024-06-27 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_inicio', models.DateTimeField()),
                ('inscricao_fim', models.DateTimeField()),
                ('sorteio_data', models.DateTimeField()),
                ('matricula_sorteados', models.DateTimeField()),
                ('matricula_geral', models.DateTimeField()),
                ('matricula_fim', models.DateTimeField()),
                ('aulas_inicio', models.DateTimeField()),
                ('aulas_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=20)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('vagas', models.IntegerField()),
                ('escolaridade', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('professor', models.CharField(max_length=100)),
                ('num_alunos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pesquisa', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nome_social_pesquisa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('data_emissao', models.DateField(blank=True, default=None, null=True)),
                ('orgao_emissor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('uf_emissao', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('filiacao', models.CharField(max_length=100)),
                ('escolaridade', models.IntegerField()),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('pcd', models.BooleanField(default=False)),
                ('ps', models.BooleanField(default=False)),
                ('ja_sorteado', models.BooleanField(default=False)),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pesquisa', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nome_social_pesquisa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('data_emissao', models.DateField()),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('uf_emissao', models.CharField(max_length=2)),
                ('filiacao', models.CharField(max_length=100)),
                ('escolaridade', models.IntegerField()),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('pcd', models.BooleanField(default=False)),
                ('ps', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default=None, null=True)),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrito_turma', to='database.turma')),
            ],
        ),
    ]
