# Generated by Django 5.1.4 on 2025-01-22 21:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_inicio', models.DateTimeField()),
                ('inscricao_fim', models.DateTimeField()),
                ('sorteio_data', models.DateTimeField()),
                ('matricula_sorte_inicio', models.DateTimeField()),
                ('matricula_sorte_fim', models.DateTimeField()),
                ('matricula_reman_inicio', models.DateTimeField()),
                ('matricula_reman_fim', models.DateTimeField()),
                ('aulas_inicio', models.DateTimeField()),
                ('aulas_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('imagem', models.ImageField(blank=True, default='cursos/default.jpg', upload_to='cursos/')),
                ('escolaridade', models.CharField(choices=[('N_ALF', 'Não Alfabetizado'), ('ALF', 'Alfabetizado'), ('EF1_INC', 'Ensino Fundamental 1 Incompleto'), ('EF1_COM', 'Ensino Fundamental 1 Completo'), ('EF2_INC', 'Ensino Fundamental 2 Incompleto'), ('EF2_COM', 'Ensino Fundamental 2 Completo'), ('EM_INC', 'Ensino Médio Incompleto'), ('EM_COM', 'Ensino Médio Completo'), ('ES_INC', 'Ensino Superior Incompleto'), ('ES_COM', 'Ensino Superior Completo'), ('PG_COM', 'Pós-Graduação Completa')], max_length=31)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco1', models.CharField(max_length=200)),
                ('endereco2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=20)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('vagas', models.IntegerField()),
                ('professor', models.CharField(max_length=100)),
                ('num_alunos', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.curso')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pesquisa', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nome_social_pesquisa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('data_emissao', models.DateField(blank=True, default=None, null=True)),
                ('orgao_emissor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('uf_emissao', models.CharField(blank=True, choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], default=None, max_length=2, null=True)),
                ('filiacao', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(choices=[('N_ALF', 'Não Alfabetizado'), ('ALF', 'Alfabetizado'), ('EF1_INC', 'Ensino Fundamental 1 Incompleto'), ('EF1_COM', 'Ensino Fundamental 1 Completo'), ('EF2_INC', 'Ensino Fundamental 2 Incompleto'), ('EF2_COM', 'Ensino Fundamental 2 Completo'), ('EM_INC', 'Ensino Médio Incompleto'), ('EM_COM', 'Ensino Médio Completo'), ('ES_INC', 'Ensino Superior Incompleto'), ('ES_COM', 'Ensino Superior Completo'), ('PG_COM', 'Pós-Graduação Completa')], max_length=31)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], max_length=2)),
                ('pcd', models.BooleanField(default=False)),
                ('ps', models.BooleanField(default=False)),
                ('ja_sorteado', models.BooleanField(default=False)),
                ('numero_inscricao', models.CharField(editable=False, max_length=14, unique=True)),
                ('data_inscricao', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 21, 37, 90108))),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pesquisa', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nome_social_pesquisa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('data_emissao', models.DateField(blank=True, default=None, null=True)),
                ('orgao_emissor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('uf_emissao', models.CharField(blank=True, choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], default=None, max_length=2, null=True)),
                ('filiacao', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(choices=[('N_ALF', 'Não Alfabetizado'), ('ALF', 'Alfabetizado'), ('EF1_INC', 'Ensino Fundamental 1 Incompleto'), ('EF1_COM', 'Ensino Fundamental 1 Completo'), ('EF2_INC', 'Ensino Fundamental 2 Incompleto'), ('EF2_COM', 'Ensino Fundamental 2 Completo'), ('EM_INC', 'Ensino Médio Incompleto'), ('EM_COM', 'Ensino Médio Completo'), ('ES_INC', 'Ensino Superior Incompleto'), ('ES_COM', 'Ensino Superior Completo'), ('PG_COM', 'Pós-Graduação Completa')], max_length=31)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], max_length=2)),
                ('pcd', models.BooleanField(default=False)),
                ('ps', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default=None, null=True)),
                ('data_matricula', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 21, 37, 91107))),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.turma')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='unidades',
            field=models.ManyToManyField(to='database.unidade'),
        ),
    ]
