# Generated by Django 5.1.4 on 2025-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
