# Generated by Django 5.0.6 on 2024-06-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_inicio', models.DateTimeField()),
                ('inscricao_fim', models.DateTimeField()),
                ('sorteio_data', models.DateTimeField()),
                ('matricula_sorteados', models.DateTimeField()),
                ('matricula_geral', models.DateTimeField()),
                ('matricula_fim', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sorteado',
        ),
    ]
