# Generated by Django 5.0.6 on 2024-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='aulas_fim',
            field=models.DateTimeField(),
        ),
    ]
