# Generated by Django 5.1.4 on 2025-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(choices=[('Não Alfabetizado', 'N Alf'), ('Alfabetizado', 'Alf'), ('Ensino Fundamental 1 Incompleto', 'Ef1 Inc'), ('Ensino Fundamental 1 Completo', 'Ef1 Com'), ('Ensino Fundamental 2 Incompleto', 'Ef2 Inc'), ('Ensino Fundamental 2 Completo', 'Ef2 Com'), ('Ensino Médio Incompleto', 'Em Inc'), ('Ensino Médio Completo', 'Em Com'), ('Ensino Superior Incompleto', 'Es Inc'), ('Ensino Superior Completo', 'Es Com'), ('Pós-Graduação Completa', 'Pg Com')], max_length=31),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf',
            field=models.CharField(choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], max_length=2),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf_emissao',
            field=models.CharField(blank=True, choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='escolaridade',
            field=models.CharField(choices=[('Não Alfabetizado', 'N Alf'), ('Alfabetizado', 'Alf'), ('Ensino Fundamental 1 Incompleto', 'Ef1 Inc'), ('Ensino Fundamental 1 Completo', 'Ef1 Com'), ('Ensino Fundamental 2 Incompleto', 'Ef2 Inc'), ('Ensino Fundamental 2 Completo', 'Ef2 Com'), ('Ensino Médio Incompleto', 'Em Inc'), ('Ensino Médio Completo', 'Em Com'), ('Ensino Superior Incompleto', 'Es Inc'), ('Ensino Superior Completo', 'Es Com'), ('Pós-Graduação Completa', 'Pg Com')], max_length=31),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='escolaridade',
            field=models.CharField(choices=[('Não Alfabetizado', 'N Alf'), ('Alfabetizado', 'Alf'), ('Ensino Fundamental 1 Incompleto', 'Ef1 Inc'), ('Ensino Fundamental 1 Completo', 'Ef1 Com'), ('Ensino Fundamental 2 Incompleto', 'Ef2 Inc'), ('Ensino Fundamental 2 Completo', 'Ef2 Com'), ('Ensino Médio Incompleto', 'Em Inc'), ('Ensino Médio Completo', 'Em Com'), ('Ensino Superior Incompleto', 'Es Inc'), ('Ensino Superior Completo', 'Es Com'), ('Pós-Graduação Completa', 'Pg Com')], max_length=31),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='uf',
            field=models.CharField(choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='uf_emissao',
            field=models.CharField(blank=True, choices=[('AC', 'Ac'), ('AL', 'Al'), ('AP', 'Ap'), ('AM', 'Am'), ('BA', 'Ba'), ('CE', 'Ce'), ('DF', 'Df'), ('ES', 'Es'), ('GO', 'Go'), ('MA', 'Ma'), ('MT', 'Mt'), ('MS', 'Ms'), ('MG', 'Mg'), ('PA', 'Pa'), ('PB', 'Pb'), ('PR', 'Pr'), ('PE', 'Pe'), ('PI', 'Pi'), ('RJ', 'Rj'), ('RN', 'Rn'), ('RS', 'Rs'), ('RO', 'Ro'), ('RR', 'Rr'), ('SC', 'Sc'), ('SP', 'Sp'), ('SE', 'Se'), ('TO', 'To')], default=None, max_length=2, null=True),
        ),
    ]
