# Generated by Django 5.0.6 on 2024-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='data_emissao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='orgao_emissor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='uf_emissao',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
