# Generated by Django 5.0.6 on 2024-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteado',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
