# Generated by Django 5.1.4 on 2025-01-10 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 15, 24, 38, 801820)),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='data_inscricao',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 15, 24, 38, 786861)),
        ),
    ]
