# Generated by Django 5.1.4 on 2025-01-16 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_aluno_data_matricula_inscrito_data_inscricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controle',
            old_name='matricula_fim',
            new_name='matricula_reman_fim',
        ),
        migrations.RenameField(
            model_name='controle',
            old_name='matricula_geral',
            new_name='matricula_reman_inicio',
        ),
        migrations.RenameField(
            model_name='controle',
            old_name='matricula_sorteados',
            new_name='matricula_sorte_fim',
        ),
        migrations.RenameField(
            model_name='controle',
            old_name='vagas_disponiveis',
            new_name='matricula_sorte_inicio',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 4, 24, 464222)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, default='cursos/default.jpg', upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='data_inscricao',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 4, 24, 463222)),
        ),
    ]
