# Generated by Django 5.0.6 on 2024-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_inscrito_data_emissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='escolaridade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='turma',
            name='escolaridade',
            field=models.CharField(max_length=2),
        ),
    ]
