# Generated by Django 5.0.6 on 2024-06-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_controle_delete_sorteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VagasDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_disponiveis', models.IntegerField()),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_turma', to='database.turma')),
            ],
        ),
    ]
