# Generated by Django 5.1 on 2024-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_aluno_data_emissao_alter_aluno_orgao_emissor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='numero_inscricao',
            field=models.CharField(default='6559.2498.6724', max_length=14),
            preserve_default=False,
        ),
    ]
