# Generated by Django 5.0.6 on 2024-06-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_turma_alunos_vagasdisponiveis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VagasDisponiveis',
        ),
    ]
