# Generated by Django 5.0.6 on 2024-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_aluno_escolaridade_alter_inscrito_escolaridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escolaridade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='escolaridade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='escolaridade',
            field=models.IntegerField(),
        ),
    ]
