# Generated by Django 5.1.4 on 2025-01-20 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_matricula_fim_controle_matricula_reman_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 17, 35, 5, 79102)),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='data_inscricao',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 17, 35, 5, 77103)),
        ),
    ]
