# Generated by Django 5.0.6 on 2024-06-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_delete_vagasdisponiveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='alunos',
            new_name='num_alunos',
        ),
    ]
