# Generated by Django 5.0.6 on 2024-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_aluno_escolaridade_alter_inscrito_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
