# Generated by Django 5.0.6 on 2024-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='horario',
            field=models.CharField(default='<django.db.models.fields.TimeField> - <django.db.models.fields.TimeField>', max_length=13),
        ),
    ]
