from django.urls import path
from .views import *

urlpatterns = [
    path('', busca_de_inscrito, name='busca_de_inscrito'),
    path('matricula/', matricula, name='matricula'),
    path('matricula/<int:inscrito_id>/', matricula, name='matricula_inscrito'),
    path('enviado/', enviado, name='enviado_int'),
    path('busca_aluno/', busca_de_aluno, name='busca_de_aluno'),
    path('editar_aluno/<int:aluno_id>/', editar_aluno, name='editar_aluno'),
    path('unidade/', unidade, name='unidade'),
    path('unidade/criar/', unidade_criar, name='unidade_criar'),
    path('unidade/editar/<int:unidade_id>/', unidade_editar, name='unidade_editar'),
    path('unidade/excluir/<int:unidade_id>/', unidade_excluir, name='unidade_excluir'),
    path('curso/', curso, name='curso'),
    path('curso/criar/', curso_criar, name='curso_criar'),
    path('curso/editar/<int:curso_id>/', curso_editar, name='curso_editar'),
    path('curso/excluir/<int:curso_id>/', curso_excluir, name='curso_excluir'),
    path('turma/', turma, name='turma'),
    path('turma/criar/', turma_criar, name='turma_criar'),
    path('turma/editar/<int:turma_id>/', turma_editar, name='turma_editar'),
    path('turma/excluir/<int:turma_id>/', turma_excluir, name='turma_excluir'),
    path('controle/', controle, name='controle'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path('reset_password_sent/', reset_password_sent_view, name='reset_password_sent'),
    path('reset/<uidb64>/<token>/', reset_password_confirm_view, name='password_reset_confirm'),
    path('reset_password_complete/', reset_password_complete_view, name='reset_password_complete'),
    path('planilhas/', planilhas, name='planilhas'),
    path('planilha_coord/', planilha_coord, name='planilha_coord'),
    path('sorteio/', sorteio, name='sorteio'),
]
