name: "Deploy para testes"

on:
  push:
    branches:
      - tests

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: "Baixar o código"
      uses: actions/checkout@v2

    - name: "Build da aplicação"
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/catatau/incuba_teste
          git clean -f -d
          git pull origin tests
          source /home/catatau/incuba_teste/venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic
          sudo systemctl restart gunicorn2
